### ISSUE TITLE
misc TODO

### ISSUE THREAD

**Issue by jgarces02** [jgarces02/FlowCT#42]
- [ ] IMPORTANT: External script to randomize analysis groups, according some spec vars.
- [ ] `barplot.cell.pops` -> default option for `color.by` (avoid errors).
- [ ] Remove cellID-dependence for subprocesses: subsampling...
- [ ] Copy `tree` methods to our code for avoiding dependences. 
- [ ] `surv.tree` not correctly exported.
- [ ] Keep proportion option in `maxstat`.
- [ ] Add UMAP options to `dim.reduction` (and change `tumap` by `umap`?)
